### ISSUE TITLE
data/spambase_train.csv description

### ISSUE THREAD

**Issue by Harry1993** [gditzler/UA-ECE-523-Sp2018#1]
Hi Prof. Ditzler,

May we have the description of data/spambase_train.csv. For example, what does each column mean? What about each row?

Thanks,
Yanmao

**Comment by gditzler** [comment]
The last column of the CSV file is the class. Each row is a data sample where every column (excluding the last) is a feature.

**Comment by stevethatsmyname** [comment]
Cool, I was going to ask the same thing!
